export default [
  {
    id: 1,
    title: "14 STROKE 16",
    image: "/assets/clouds-image-1.png",
    description: "An online magazine for a creative collective.",
    url: "https://www.14stroke16.com/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
  {
    id: 2,
    title: "Lorem Ipsum",
    image: "/assets/clouds-image-2.png",
    description: "A Shopify E-Commerce store for a luxury clothing brand.",
    url: "https://charity-website-eight.vercel.app/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
  {
    id: 3,
    title: "From Scratch",
    image: "/assets/clouds-image-1.png",
    description: "A charity website.",
    url: "https://www.14stroke16.com/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
  {
    id: 4,
    title: "Lorem Ipsum",
    image: "/assets/clouds-image-2.png",
    description: "A Shopify E-Commerce store for a luxury clothing brand.",
    url: "https://charity-website-eight.vercel.app/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
  {
    id: 5,
    title: "From Scratch",
    image: "/assets/clouds-image-1.png",
    description: "A charity website.",
    url: "https://www.14stroke16.com/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
  {
    id: 6,
    title: "14 STROKE 16",
    image: "/assets/clouds-image-2.png",
    description: "An online magazine for a creative collective.",
    url: "https://www.14stroke16.com/",
    languages: ["Contentful", "NextJS", "TailwindCSS"],
  },
];
